name: Release Note

on:
    release:
        types: [published]

jobs:
    release-note:
        if: startsWith(github.ref, 'refs/tags/')
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Create changelog
              id: github_release
              uses: mikepenz/release-changelog-builder-action@v1.4.2
              with:
                  configuration: "configuration.json"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Update release
              uses: ncipollo/release-action@v1
              with:
                  allowUpdates: true
                  body: ${{ steps.github_release.outputs.changelog }}
                  token: ${{ secrets.GITHUB_TOKEN }}
                  prerelease: ${{ contains(github.ref, 'rc') }}